### ISSUE TITLE
'API Reference' page issue

### ISSUE THREAD

**Issue by nishanthvallambatla** [angulardart-community/site-angulardart#32]
From URL: https://angulardart.xyz/api
Many of the links in Angular library documentation (https://pub.dev/documentation/angular/6.0.1/angular/angular-library.html) do not work! They throw 404 Not Found errors.

Example links which did not work:
https://pub.dev/documentation/angular_compiler/1.0.1/v1_src_metadata/AfterChanges-class.html
https://pub.dev/documentation/angular_compiler/1.0.1/v1_src_metadata/AfterContentChecked-class.html

**Comment by GZGavinZhao** [comment]
@nishanthvallambatla Gotcha.

**Comment by GZGavinZhao** [comment]
Oh wait, there is actually nothing we can do on our side because this is the package maintained by the official team :( I guess you have to speak with them at the official repo: https://github.com/angulardart/angular
