### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by coolgk** [angulardart-community/site-angulardart#34]
example code: "lib/src/hero_list_component.html (add)" on https://angulardart.xyz/tutorial/toh-pt6#add-the-ability-to-add-heroes contains multiple expressions for the (click) event: <button **(click)="add(heroName.value); heroName.value=''"**> causing compilation errors. need to move the logic into the "add()" function.

same problem for https://angulardart.xyz/tutorial/toh-pt6#add-the-ability-to-delete-a-hero  for the delete example: <button class="delete" **(click)="delete(hero); $event.stopPropagation()"**>x</button>. need to move the logic into the delete() function.

**Comment by GZGavinZhao** [comment]
What Angular version and Dart version are you on? Could you please provide me your `pubspec.yaml` file (only the dependency section is enough) and your `dart --version` output?

**Comment by coolgk** [comment]
`name: heroes
description: A web app that uses AngularDart Components
# version: 0.0.``
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2
  angular_forms: ^3.0.0
  angular_router: ^2.0.0-alpha
  http: ^0.12.0
  stream_transform: ^1.2.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  meta: <1.7.0 # As of 07/12/2021, Dart throws errors if meta is 1.7.0 or above
  pedantic: ^1.9.0
  test: ^1.6.3
`

`dart --version
Dart SDK version: 2.13.4 (stable) (Unknown timestamp) on "linux_x64"`
